// Code generated by goctl. DO NOT EDIT.
// Source: api.proto

package server

import (
	"context"

	"st-key-manager/internal/logic"
	"st-key-manager/internal/svc"
	"st-key-manager/keymanager"
)

type KeymanagerServer struct {
	svcCtx *svc.ServiceContext
	keymanager.UnimplementedKeymanagerServer
}

func NewKeymanagerServer(svcCtx *svc.ServiceContext) *KeymanagerServer {
	return &KeymanagerServer{
		svcCtx: svcCtx,
	}
}

func (s *KeymanagerServer) GetKey(ctx context.Context, in *keymanager.GetKeyRequest) (*keymanager.GetKeyReply, error) {
	l := logic.NewGetKeyLogic(ctx, s.svcCtx)
	return l.GetKey(in)
}
