// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.3
// source: proto/api.proto

package keymanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KeymanagerClient is the client API for Keymanager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeymanagerClient interface {
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyReply, error)
}

type keymanagerClient struct {
	cc grpc.ClientConnInterface
}

func NewKeymanagerClient(cc grpc.ClientConnInterface) KeymanagerClient {
	return &keymanagerClient{cc}
}

func (c *keymanagerClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyReply, error) {
	out := new(GetKeyReply)
	err := c.cc.Invoke(ctx, "/keymanager.Keymanager/GetKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeymanagerServer is the server API for Keymanager service.
// All implementations must embed UnimplementedKeymanagerServer
// for forward compatibility
type KeymanagerServer interface {
	GetKey(context.Context, *GetKeyRequest) (*GetKeyReply, error)
	mustEmbedUnimplementedKeymanagerServer()
}

// UnimplementedKeymanagerServer must be embedded to have forward compatible implementations.
type UnimplementedKeymanagerServer struct {
}

func (UnimplementedKeymanagerServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKeymanagerServer) mustEmbedUnimplementedKeymanagerServer() {}

// UnsafeKeymanagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeymanagerServer will
// result in compilation errors.
type UnsafeKeymanagerServer interface {
	mustEmbedUnimplementedKeymanagerServer()
}

func RegisterKeymanagerServer(s grpc.ServiceRegistrar, srv KeymanagerServer) {
	s.RegisterService(&Keymanager_ServiceDesc, srv)
}

func _Keymanager_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeymanagerServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keymanager.Keymanager/GetKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeymanagerServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Keymanager_ServiceDesc is the grpc.ServiceDesc for Keymanager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Keymanager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keymanager.Keymanager",
	HandlerType: (*KeymanagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _Keymanager_GetKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
